name: Generate images

on:
  push:
    branches: [ master ]

jobs:
  generate-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.4.16', '8.0.0', '8.0.2', '8.0.3' ]

    name: Generating PHP ${{ matrix.php }} image

    steps:
    - name: Pull repo
      uses: actions/checkout@v2

    - name: Generate PHP_VERSION file
      run: echo "${{ matrix.php }}" > PHP_VERSION
      shell: bash

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        
        image-name: php-test-env # Provide Docker image name
        image-tag: ${{ matrix.php }} # Provide Docker image tag
