name: Generate images

on:
  push:
    branches: [ master ]

jobs:
  generate-image:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.4.1', '7.4.7', '7.4.16', '8.0.0', '8.0.2', '8.0.3' ]

    name: Generating PHP ${{ matrix.php }} image

    steps:
    - name: Pull repo
      uses: actions/checkout@v2

    - name: Setup PHP version
      run: |
        MY_VER=$(grep "${{ matrix.php }}" PHP_VERSIONS | xargs)
        IFS='=' read -ra MY_VER <<< "$MY_VER"
        MY_VER=${MY_VER[1]}
        sed "s/\[\[version\]\]/$MY_VER/g" Dockerfile > Dockerfile.tmp; mv Dockerfile.tmp Dockerfile
        head -2 Dockerfile
      shell: bash

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        
        image-name: php-test-env # Provide Docker image name
        image-tag: ${{ matrix.php }} # Provide Docker image tag
